<a href="https://colab.research.google.com/github/ict3104-p2-team08/ict3104-p2-team08/blob/dev/3104_T08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity Detection ML Test

## 1. Prerequisites

This section provides the setting up of the environment

In [ ]:
!pip install torch -f https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
!pip install torchaudio -f https://download.pytorch.org/whl/cu113/torchaudio-0.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
!pip install torchsummary==1.5.1 torchtext==0.13.1 torchvision -f https://download.pytorch.org/whl/cu113/torchvision-0.13.1%2Bcu113-cp37-cp37m-linux_x86_64.whl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/cu113/torchaudio-0.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://download.pytorch.org/whl/cu113/torchvision-0.13.1%2Bcu113-cp37-cp37m-linux_x86_64.whl


In [ ]:
!git clone https://github.com/v-iashin/video_features.git
!pip install omegaconf==2.0.6

fatal: destination path 'video_features' already exists and is not an empty directory.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Imports widgets for jupyter
try:
    import piplite
    piplite.install(['ipywidgets'])
except ImportError:
    pass

## 2. Toggling of pipelines

This section shows the toggling of dependencies between TSU and STEP

In [ ]:
#insert code here

## 3. Data exploration

This section load and display video data from the Toyota Smarthome (TSU) project

In [ ]:
#import tsu video files
import os
FOLDER_PATH = 'input_files'
ROOT_PATH = '/content/data'

file_list = os.listdir(os.path.join(ROOT_PATH, FOLDER_PATH))

In [ ]:
#tsu video files to display in dropdown
from ipywidgets import  Dropdown, widgets

w = widgets.Dropdown(
    options= file_list,
)

def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        print(change['new'])

w.observe(on_change)

display(w)

Dropdown(options=('P02T05C05.mp4', 'P02T02C06.mp4', 'P02T02C03.mp4', 'P02T10C06.mp4', 'P02T09C05.mp4', 'P02T03…

P02T02C06.mp4


In [ ]:
#display video 
from IPython.display import HTML
from base64 import b64encode

video_path = '/content/data/input_files/%' + w.value

locate= "" 

for i in video_path: 
   if i=='%': 
       pass
   else: 
       locate+=i 

def show_video(locate, video_width = 500):
  video_file = open(locate, "r+b").read()
  video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
  return HTML(f"""<video width={video_width} controls><source src="{video_url}"></video>""")
  
show_video(locate)

In [ ]:
#only run it for the first time
%cd video_features

/content/video_features


In [ ]:
#extract to I3D feature file
from models.i3d.extract_i3d import ExtractI3D
from utils.utils import build_cfg_path
from omegaconf import OmegaConf
import torch

# Select the feature type
feature_type = 'i3d'
args = OmegaConf.load(build_cfg_path(feature_type))
args.video_paths = ['/content/data/input_files/P02T02C06.mp4']
args.flow_type = 'raft'

extractor = ExtractI3D(args)
print(locate)

# Extract features
for video_path in args.video_paths:
    print(f'Extracting for {video_path}')
    feature_dict = extractor.extract(video_path)
    [(print(k), print(v.shape), print(v)) for k, v in feature_dict.items()]

/content/data/input_files/P02T02C06.mp4
Extracting for /content/data/input_files/P02T02C06.mp4


/usr/local/lib/python3.7/dist-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


rgb
(11, 1024)
[[0.20739523 0.72059214 0.22846813 ... 0.13607328 0.03399111 0.08541902]
 [0.19407573 0.6217134  0.09731438 ... 0.08541699 0.0068772  0.12624256]
 [0.15689622 0.65015948 0.12548588 ... 0.22583438 0.00084241 0.14918594]
 ...
 [0.14434917 0.69237942 0.23985368 ... 0.19039093 0.03904627 0.09985807]
 [0.15447114 0.66078436 0.12696403 ... 0.20725532 0.00994472 0.11938995]
 [0.14333992 0.67311281 0.07387753 ... 0.1581721  0.00531566 0.13367005]]
flow
(11, 1024)
[[0.04966787 0.02747902 0.03200795 ... 0.00117544 0.00866363 0.00070588]
 [0.02951456 0.11375064 0.08617321 ... 0.13416514 0.00996939 0.10337494]
 [0.05398095 0.05012308 0.03169821 ... 0.21530373 0.01029605 0.14926349]
 ...
 [0.04805181 0.03144133 0.03666719 ... 0.07257506 0.00305848 0.09575627]
 [0.05060966 0.02914934 0.03825664 ... 0.0504254  0.01192183 0.05661202]
 [0.03146445 0.02472811 0.02506865 ... 0.03133011 0.00716995 0.00086102]]
fps
()
25.0
timestamps_ms
(11,)
[ 2560.  5120.  7680. 10240. 12800. 15360. 17920.

## 4. Inference with pretrained model

This section shows

In [ ]:
#insert codes here

## 5. Testing and evaluating trained models

This section shows

In [ ]:
#insert codes here

## 6. Training of new model

This section shows

In [ ]:
#insert codes here